
export enum BookReadsStatus {
    INACTIVE = "INACTIVE",
    PENDING_TO_BUY = "PENDING_TO_BUY",
    PENDING_TO_READ = "PENDING_TO_READ",
    IN_PROGRESS = "IN_PROGRESS",
    INCOMPLETE = "INCOMPLETE",
    COMPLETE = "COMPLETE"
}